import type { LevelConfig } from "@/game/core/types";

// ─────────────────────────────────────────────────────────────────────────
// THE LEVEL SPINE. Everything about the game's flow is driven by this ordered
// array. To add/remove a level, edit ONLY this file — the number of levels
// appears nowhere else in engine code. The last element automatically ends the
// run (victory), because the loop checks `currentLevel < LEVELS.length`.
//
// Arc: escape the pit → cross the cursed wild (wood, mire, pass) → fight through
// Blackhall Castle (gate → halls → crypt → ramparts → antechamber) → the Throne.
// Difficulty rises across the run: turn budget shrinks, monsters grow tougher
// and more numerous, light dwindles, coins richen to fund the climb.
// ─────────────────────────────────────────────────────────────────────────
export const LEVELS: LevelConfig[] = [
  {
    id: "dungeon_depths",
    title: "The Pit",
    biome: "dungeon",
    palette: { wall: "#6b6b7c", floor: "#3b3b46", accent: "#ffe14d" },
    mapWidth: 40,
    mapHeight: 24,
    generator: "digger",
    monsterBudget: 6,
    spawnTable: [
      { monsterId: "rat", weight: 6 },
      { monsterId: "bat", weight: 4 },
    ],
    turnLimit: 420,
    itemDropCount: 4,
    dropTable: [
      { itemId: "c_gold", weight: 6 },
      { itemId: "p_heal", weight: 3 },
      { itemId: "w_short", weight: 2 },
      { itemId: "i_torch", weight: 1 },
    ],
    coinRichness: 1.15,
    baseLightRadius: 8,
    trapCount: 3,
    doorCount: 2,
    forageCount: 3,
    goal: { type: "reachLocation" },
    narration:
      "You haul yourself out of the pit into cold night air. No stars — only a black wall of trees ahead, whispering. The Blackwood. Somewhere in it lies the path the dead don't want you to find.",
    shopTier: 1,
  },
  {
    id: "blackwood",
    title: "The Blackwood",
    biome: "forest",
    palette: { wall: "#3f7a45", floor: "#2f4326", accent: "#7fdfff" },
    mapWidth: 48,
    mapHeight: 30,
    generator: "cellular",
    monsterBudget: 9,
    spawnTable: [
      { monsterId: "rat", weight: 3 },
      { monsterId: "bat", weight: 4 },
      { monsterId: "goblin", weight: 4 },
      { monsterId: "spider", weight: 3 },
    ],
    turnLimit: 380,
    itemDropCount: 4,
    dropTable: [
      { itemId: "c_gold", weight: 6 },
      { itemId: "p_heal", weight: 3 },
      { itemId: "a_leather", weight: 2 },
    ],
    coinRichness: 1.15,
    baseLightRadius: 6,
    trapCount: 2,
    waterCount: 10,
    forageCount: 6,
    goal: { type: "collectX", questTag: "moonstone", count: 3 },
    narration:
      "The three shards flare as one, and a silver thread pulls you downward — toward a reek of rot and black standing water. The Mire. Whatever the dead are guarding, the only path runs through it.",
    shopTier: 2,
  },
  {
    id: "the_mire",
    title: "The Mire",
    biome: "marsh",
    palette: { wall: "#5f7a3c", floor: "#2e3a28", accent: "#7fdfff" },
    mapWidth: 50,
    mapHeight: 30,
    generator: "cellular",
    monsterBudget: 10,
    spawnTable: [
      { monsterId: "spider", weight: 4 },
      { monsterId: "imp", weight: 2 },
      { monsterId: "goblin", weight: 3 },
    ],
    turnLimit: 350,
    itemDropCount: 4,
    dropTable: [
      { itemId: "c_gold", weight: 6 },
      { itemId: "p_heal", weight: 3 },
      { itemId: "p_detect", weight: 1 },
      { itemId: "i_torch", weight: 1 },
    ],
    coinRichness: 1.15,
    baseLightRadius: 6,
    trapCount: 3,
    forageCount: 6,
    waterCount: 46,
    oilCount: 16,
    eliteChance: 0.1,
    altarCount: 1,
    goal: { type: "reachLocation" },
    narration:
      "You drag onto the last stone of the causeway, mud to the knee, and the air turns suddenly cold and clean. Ahead the ground climbs into ice and bare rock — the Frostspine Pass — and something enormous is breathing on the wind.",
    shopTier: 3,
  },
  {
    id: "frostspine_pass",
    title: "The Frostspine Pass",
    biome: "mountain",
    palette: { wall: "#7d8ea0", floor: "#40454f", accent: "#a9e0ff" },
    mapWidth: 52,
    mapHeight: 32,
    generator: "cellular",
    monsterBudget: 12,
    spawnTable: [
      { monsterId: "goblin", weight: 5 },
      { monsterId: "skeleton", weight: 5 },
    ],
    turnLimit: 320,
    itemDropCount: 3,
    dropTable: [
      { itemId: "c_gold", weight: 6 },
      { itemId: "p_heal", weight: 2 },
      { itemId: "w_axe", weight: 1 },
    ],
    coinRichness: 1.25,
    baseLightRadius: 5,
    trapCount: 3,
    waterCount: 18,
    forageCount: 5,
    eliteChance: 0.12,
    goal: { type: "killTarget", monsterId: "frost_troll" },
    narration:
      "Gorm topples off the bridge into the white below, and the way is open. Across the chasm the gates of Blackhall Castle loom — iron and old bone — and their wardens have already seen you.",
    shopTier: 4,
  },
  {
    id: "iron_gate",
    title: "The Iron Gate",
    biome: "castle",
    palette: { wall: "#6a5c6e", floor: "#2e2833", accent: "#d24a4a" },
    mapWidth: 52,
    mapHeight: 32,
    generator: "digger",
    monsterBudget: 13,
    spawnTable: [
      { monsterId: "skeleton", weight: 4 },
      { monsterId: "ghoul", weight: 4 },
      { monsterId: "gargoyle", weight: 2 },
      { monsterId: "gate_captain", weight: 1 },
    ],
    turnLimit: 360,
    itemDropCount: 4,
    dropTable: [
      { itemId: "c_gold", weight: 6 },
      { itemId: "p_heal", weight: 2 },
      { itemId: "p_bomb", weight: 1 },
    ],
    coinRichness: 1.3,
    baseLightRadius: 5,
    trapCount: 5,
    crackedWallCount: 4,
    doorCount: 3,
    forageCount: 1,
    eliteChance: 0.15,
    altarCount: 1,
    goal: { type: "killCount", count: 8 },
    narration:
      "The last of the gate's wardens falls and the portcullis grinds upward on rusted chains. Beyond spreads the great hall of Blackhall — cold, vast, and thick with the castle's restless dead.",
    shopTier: 5,
  },
  {
    id: "great_hall",
    title: "The Great Hall",
    biome: "castle",
    palette: { wall: "#5c4b70", floor: "#342d40", accent: "#c04cff" },
    mapWidth: 56,
    mapHeight: 34,
    generator: "digger",
    monsterBudget: 14,
    spawnTable: [
      { monsterId: "skeleton", weight: 4 },
      { monsterId: "zombie", weight: 3 },
      { monsterId: "ghoul", weight: 4 },
      { monsterId: "wraith", weight: 2 },
    ],
    turnLimit: 375,
    itemDropCount: 4,
    dropTable: [
      { itemId: "c_gold", weight: 6 },
      { itemId: "p_gheal", weight: 2 },
      { itemId: "a_chain", weight: 1 },
    ],
    coinRichness: 1.4,
    baseLightRadius: 5,
    trapCount: 4,
    oilCount: 12,
    crackedWallCount: 4,
    doorCount: 3,
    forageCount: 1,
    eliteChance: 0.15,
    altarCount: 2,
    goal: { type: "collectX", questTag: "sigil", count: 3 },
    narration:
      "The three dusk-sigils lock into the crypt door and it swings inward on a breath of grave-air. Down there, the last kings hid the one blade that can still cut the night: the Sunblade.",
    shopTier: 6,
  },
  {
    id: "sunken_crypt",
    title: "The Sunken Crypt",
    biome: "crypt",
    palette: { wall: "#6a6a5a", floor: "#262620", accent: "#9fe0b0" },
    mapWidth: 54,
    mapHeight: 34,
    generator: "digger",
    monsterBudget: 15,
    spawnTable: [
      { monsterId: "ghoul", weight: 5 },
      { monsterId: "skeleton", weight: 4 },
      { monsterId: "wraith", weight: 3 },
    ],
    turnLimit: 380,
    itemDropCount: 3,
    dropTable: [
      { itemId: "c_gold", weight: 6 },
      { itemId: "p_gheal", weight: 2 },
      { itemId: "p_detect", weight: 2 },
      { itemId: "i_lantern", weight: 1 },
    ],
    coinRichness: 1.5,
    baseLightRadius: 3,
    trapCount: 8,
    forageCount: 2,
    oilCount: 10,
    crackedWallCount: 3,
    doorCount: 2,
    eliteChance: 0.18,
    altarCount: 1,
    goal: { type: "findItem", questTag: "sunblade" },
    narration:
      "Your hand closes on the Sunblade and warmth floods your arm for the first time in days. There is no way up but the ramparts — open to the dead sky, and to whatever wheels across it.",
    shopTier: 7,
  },
  {
    id: "ramparts",
    title: "The Ramparts",
    biome: "castle",
    palette: { wall: "#4a5a72", floor: "#232a38", accent: "#a9e0ff" },
    mapWidth: 54,
    mapHeight: 32,
    generator: "digger",
    monsterBudget: 14,
    spawnTable: [
      { monsterId: "wraith", weight: 4 },
      { monsterId: "gargoyle", weight: 3 },
      { monsterId: "skeleton", weight: 3 },
    ],
    turnLimit: 260,
    itemDropCount: 4,
    dropTable: [
      { itemId: "c_gold", weight: 6 },
      { itemId: "p_gheal", weight: 2 },
      { itemId: "p_bomb", weight: 1 },
    ],
    coinRichness: 1.6,
    baseLightRadius: 6,
    trapCount: 2,
    forageCount: 3,
    waterCount: 12,
    eliteChance: 0.2,
    altarCount: 1,
    goal: { type: "survive", turns: 34 },
    narration:
      "You hold the ramparts until the assault breaks and the wind finally dies to nothing. A single black door stands open ahead — the antechamber of the throne — and Malachar's Herald waits before it, wreathed in cold fire.",
    shopTier: 8,
  },
  {
    id: "antechamber",
    title: "The Dusk Antechamber",
    biome: "castle",
    palette: { wall: "#7a5c4a", floor: "#33281f", accent: "#ffd24d" },
    mapWidth: 48,
    mapHeight: 30,
    generator: "digger",
    monsterBudget: 13,
    spawnTable: [
      { monsterId: "wraith", weight: 4 },
      { monsterId: "skeleton", weight: 3 },
      { monsterId: "ghoul", weight: 3 },
    ],
    turnLimit: 350,
    itemDropCount: 4,
    dropTable: [
      { itemId: "c_gold", weight: 6 },
      { itemId: "p_gheal", weight: 2 },
      { itemId: "p_bomb", weight: 1 },
    ],
    coinRichness: 1.8,
    baseLightRadius: 5,
    trapCount: 3,
    crackedWallCount: 3,
    doorCount: 2,
    forageCount: 1,
    eliteChance: 0.2,
    goal: { type: "killTarget", monsterId: "herald" },
    narration:
      "The Herald falls to ash and the black door yields. Beyond, a stair of black marble climbs to the Throne of Dusk. Malachar is waiting. End this.",
    shopTier: 9,
  },
  {
    id: "throne_of_dusk",
    title: "The Throne of Dusk",
    biome: "throne",
    palette: { wall: "#74494a", floor: "#3a2b2b", accent: "#ffd700" },
    mapWidth: 44,
    mapHeight: 28,
    generator: "digger",
    monsterBudget: 11,
    spawnTable: [
      { monsterId: "wraith", weight: 5 },
      { monsterId: "skeleton", weight: 4 },
    ],
    turnLimit: 310,
    itemDropCount: 3,
    dropTable: [
      { itemId: "c_gold", weight: 5 },
      { itemId: "p_gheal", weight: 3 },
    ],
    coinRichness: 2.0,
    baseLightRadius: 5,
    trapCount: 2,
    doorCount: 2,
    goal: { type: "killTarget", monsterId: "lich" },
    // Final level: this narration is unused for transition (the Victory screen
    // shows VICTORY.body instead), but kept for completeness.
    narration: "The last of the dark drains from the hall.",
    shopTier: null,
  },
];

export const LEVEL_COUNT = LEVELS.length;
